openapi: 3.0.0
x-stoplight:
  id: 4qqp6vkvdx7s7
info:
  title: todos-service
  version: '1.0'
  description: Сервис задач
  contact:
    name: Todo service API
    url: 'http://localhost:3000/todos'
    email: golomazov@mcb.ru
servers:
  - url: 'http://localhost:3000'
tags:
  - name: todo
    description: 'Todo details data'
paths:
  /todos:
    post:
      summary: Создание задачи
      tags:
        - todo
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Todo.yaml
      operationId: createTodo
      description: Создание задачи
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/Todo.yaml
    get:
      summary: Получение списка задач
      description: Получение списка текущих задач
      tags:
        - todo
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/dto/TodoList.yaml
      operationId: fetchTodos
  /todos/{todoId}:
    parameters:
      - $ref: '#/components/parameters/todoId'
    get:
      description: 'Получение задачи по ID'
      operationId: fetchTodoId
      tags:
        - todo
      responses:
        '200':
          description: OK
security:
  - jwt: []
components:
  schemas: {}
  parameters:
    todoId:
      name: todoId
      in: path
      required: true
      description: ID пользователя
      schema:
        type: string
        format: uuid
  securitySchemes:
    jwt:
      type: http
      scheme: bearer
      bearerFormat: JWT
